name: timelines_plus
description: "Just updated version of Timelines package. Note: this is just updated version of this package: https://pub.dev/packages/timelines "
version: 1.0.3
homepage:

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
